# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
parameters:
- name: RunTests
  default: true

trigger: none
pr:
  branches:
    include:
    - main
    - release-*

pool:
    vmImage: 'ubuntu-22.04'
jobs:
- job: RunTests
  timeoutInMinutes: 0
  strategy: 
    maxParallel: 5
    matrix:      
      Helm_3_19_5_single: 
        HelmVersion: "3.19.5"
        TestType: single
      Helm_3_20_1_single: 
        HelmVersion: "3.20.1"
        TestType: single
      Helm_4_0_5_single: 
        HelmVersion: "4.0.5"
        TestType: single
      Helm_4_1_3_single: 
        HelmVersion: "4.1.3"
        TestType: single
      Helm_4_1_3_multi: 
        HelmVersion: "4.1.3"
        TestType: multi
      
  steps:
  - template: azure-pipelines-test.yml  # Template reference
    parameters:
      RunTests: ${{ parameters.RunTests }}