# HTTPRoute

Test creation of objects and features.

* Prepare default test case for kind "HTTPRoute"

## Render and Validate

* Lint and Render
* Expected number of "1" objects were rendered on top of basic objects count

## Metadata

* Check basic metadata functionality

## Full Example
* Lint and Render
* Set test object to "release-name-hull-test-full-example"
* Test Object has key "spec§parentRefs§0§group" with value "group1"
* Test Object has key "spec§parentRefs§0§kind" with value "kind1"
* Test Object has key "spec§parentRefs§0§namespace" with value "namespace1"
* Test Object has key "spec§parentRefs§0§name" with value "name1"
* Test Object has key "spec§parentRefs§0§sectionName" with value "testsection1"
* Test Object has key "spec§parentRefs§0§port" with integer value "1"
* Test Object has key "spec§parentRefs§1§group" with value "group2"
* Test Object has key "spec§parentRefs§1§kind" with value "kind2"
* Test Object has key "spec§parentRefs§1§namespace" with value "namespace2"
* Test Object has key "spec§parentRefs§1§name" with value "name2"
* Test Object has key "spec§parentRefs§1§sectionName" with value "testsection2"
* Test Object has key "spec§parentRefs§1§port" with integer value "2"
* Test Object has key "spec§hostnames§host1" with value "host1"
* Test Object has key "spec§hostnames§host2" with value "host2"
* Test Object has key "spec§rules§0§name" with value "one-name"
* Test Object has key "spec§rules§0§timeouts§request" with value "135s"
* Test Object has key "spec§rules§0§timeouts§backendRequest" with value "531s"
* Test Object has key "spec§rules§0§retry§codes§0" with integer value "500"
* Test Object has key "spec§rules§0§retry§codes§1" with integer value "502"
* Test Object has key "spec§rules§0§retry§codes§2" with integer value "504"
* Test Object has key "spec§rules§0§retry§attempts" with integer value "4"
* Test Object has key "spec§rules§0§retry§backoff" with value "931m"
* Test Object has key "spec§rules§0§sessionPersistence§absoluteTimeout" with value "456s"
* Test Object has key "spec§rules§0§sessionPersistence§absoluteTimeout" with value "456s"
* Test Object has key "spec§rules§0§sessionPersistence§type" with value "Cookie"
* Test Object has key "spec§rules§0§sessionPersistence§idleTimeout" with value "123s"
* Test Object has key "spec§rules§0§sessionPersistence§sessionName" with value "sessionname"
* Test Object has key "spec§rules§0§sessionPersistence§cookieConfig§lifetimeType" with value "Permanent"
* Test Object has key "spec§rules§0§matches§0§method" with value "CONNECT"
* Test Object has key "spec§rules§0§matches§0§headers§0§name" with value "firstheader"
* Test Object has key "spec§rules§0§matches§0§headers§0§type" with value "Exact"
* Test Object has key "spec§rules§0§matches§0§headers§0§value" with value "someheadervalue1"
* Test Object has key "spec§rules§0§matches§0§path§type" with value "Exact"
* Test Object has key "spec§rules§0§matches§0§path§value" with value "/onepathmatch"
* Test Object has key "spec§rules§0§matches§0§queryParams§0§type" with value "Exact"
* Test Object has key "spec§rules§0§matches§0§queryParams§0§name" with value "oneparam1"
* Test Object has key "spec§rules§0§matches§0§queryParams§0§value" with value "oneparam1val"
* Test Object has key "spec§rules§0§matches§0§queryParams§1§type" with value "Exact"
* Test Object has key "spec§rules§0§matches§0§queryParams§1§name" with value "oneparam2"
* Test Object has key "spec§rules§0§matches§0§queryParams§1§value" with value "oneparam2val"
* Test Object has key "spec§rules§0§matches§1§method" with value "GET"
* Test Object has key "spec§rules§0§matches§1§headers§0§name" with value "secheader"
* Test Object has key "spec§rules§0§matches§1§headers§0§type" with value "Exact"
* Test Object has key "spec§rules§0§matches§1§headers§0§value" with value "secheadervalue2"
* Test Object has key "spec§rules§0§matches§1§path§type" with value "PathPrefix"
* Test Object has key "spec§rules§0§matches§1§path§value" with value "/twopathmatch"
* Test Object has key "spec§rules§0§matches§1§queryParams§0§type" with value "Exact"
* Test Object has key "spec§rules§0§matches§1§queryParams§0§name" with value "twoparam1"
* Test Object has key "spec§rules§0§matches§1§queryParams§0§value" with value "twoparam1val"
* Test Object has key "spec§rules§0§matches§1§queryParams§1§type" with value "Exact"
* Test Object has key "spec§rules§0§matches§1§queryParams§1§name" with value "twoparam2"
* Test Object has key "spec§rules§0§matches§1§queryParams§1§value" with value "twoparam2val"
* Test Object has key "spec§rules§0§filters§0§type" with value "ExtensionRef"
* Test Object has key "spec§rules§0§filters§0§requestHeaderModifier§set§0§name" with value "Accept1"
* Test Object has key "spec§rules§0§filters§0§requestHeaderModifier§set§0§value" with value "json1"
* Test Object has key "spec§rules§0§filters§0§requestHeaderModifier§set§1§name" with value "Accept2"
* Test Object has key "spec§rules§0§filters§0§requestHeaderModifier§set§1§value" with value "json2"
* Test Object has key "spec§rules§0§filters§0§requestHeaderModifier§add§0§name" with value "Accept3"
* Test Object has key "spec§rules§0§filters§0§requestHeaderModifier§add§0§value" with value "json3"
* Test Object has key "spec§rules§0§filters§0§requestHeaderModifier§add§1§name" with value "Accept4"
* Test Object has key "spec§rules§0§filters§0§requestHeaderModifier§add§1§value" with value "json4"
* Test Object has key "spec§rules§0§filters§0§requestHeaderModifier§remove§0" with value "oldheader1"
* Test Object has key "spec§rules§0§filters§0§requestHeaderModifier§remove§1" with value "oldheader2"
* Test Object has key "spec§rules§0§filters§0§requestHeaderModifier§set§0§name" with value "Accept1"
* Test Object has key "spec§rules§0§filters§0§responseHeaderModifier§set§0§value" with value "json1"
* Test Object has key "spec§rules§0§filters§0§responseHeaderModifier§set§1§name" with value "Accept2"
* Test Object has key "spec§rules§0§filters§0§responseHeaderModifier§set§1§value" with value "json2"
* Test Object has key "spec§rules§0§filters§0§responseHeaderModifier§add§0§name" with value "Accept3"
* Test Object has key "spec§rules§0§filters§0§responseHeaderModifier§add§0§value" with value "json3"
* Test Object has key "spec§rules§0§filters§0§responseHeaderModifier§add§1§name" with value "Accept4"
* Test Object has key "spec§rules§0§filters§0§responseHeaderModifier§add§1§value" with value "json4"
* Test Object has key "spec§rules§0§filters§0§responseHeaderModifier§remove§0" with value "oldheader1"
* Test Object has key "spec§rules§0§filters§0§responseHeaderModifier§remove§1" with value "oldheader2"
* Test Object has key "spec§rules§0§filters§0§requestMirror§backendRef§group" with value "group1"
* Test Object has key "spec§rules§0§filters§0§requestMirror§backendRef§kind" with value "kind1"
* Test Object has key "spec§rules§0§filters§0§requestMirror§backendRef§namespace" with value "namespace1"
* Test Object has key "spec§rules§0§filters§0§requestMirror§backendRef§name" with value "name1"
* Test Object has key "spec§rules§0§filters§0§requestMirror§backendRef§port" with integer value "1"
* Test Object has key "spec§rules§0§filters§0§requestMirror§percent" with integer value "66"
* Test Object has key "spec§rules§0§filters§0§requestMirror§fraction§numerator" with integer value "11"
* Test Object has key "spec§rules§0§filters§0§requestMirror§fraction§denominator" with integer value "22"
* Test Object has key "spec§rules§0§filters§0§requestRedirect§scheme" with value "http"
* Test Object has key "spec§rules§0§filters§0§requestRedirect§hostname" with value "rrhostname"
* Test Object has key "spec§rules§0§filters§0§requestRedirect§path§type" with value "ReplaceFullPath"
* Test Object has key "spec§rules§0§filters§0§requestRedirect§path§replaceFullPath" with value "replaceme22"
* Test Object has key "spec§rules§0§filters§0§requestRedirect§path§replacePrefixMatch" with value "replacemeprefix22"
* Test Object has key "spec§rules§0§filters§0§requestRedirect§port" with integer value "525"
* Test Object has key "spec§rules§0§filters§0§requestRedirect§statusCode" with integer value "301"
* Test Object has key "spec§rules§0§filters§0§urlRewrite§hostname" with value "www.lot.com"
* Test Object has key "spec§rules§0§filters§0§urlRewrite§path§type" with value "ReplaceFullPath"
* Test Object has key "spec§rules§0§filters§0§urlRewrite§path§replaceFullPath" with value "replaceme"
* Test Object has key "spec§rules§0§filters§0§urlRewrite§path§replacePrefixMatch" with value "replacemeprefix"
* Test Object has key "spec§rules§0§filters§0§extensionRef§group" with value "group1"
* Test Object has key "spec§rules§0§filters§0§extensionRef§kind" with value "kind1"
* Test Object has key "spec§rules§0§filters§0§extensionRef§name" with value "name1"
* Test Object has key "spec§rules§0§backendRefs§0§group" with value "group1"
* Test Object has key "spec§rules§0§backendRefs§0§kind" with value "kind1"
* Test Object has key "spec§rules§0§backendRefs§0§namespace" with value "namespace1"
* Test Object has key "spec§rules§0§backendRefs§0§name" with value "name1"
* Test Object has key "spec§rules§0§backendRefs§0§weight" with integer value "965"
* Test Object has key "spec§rules§0§backendRefs§0§port" with integer value "1"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§type" with value "ExtensionRef"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§requestHeaderModifier§set§0§name" with value "Accept1"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§requestHeaderModifier§set§0§value" with value "json1"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§requestHeaderModifier§set§1§name" with value "Accept2"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§requestHeaderModifier§set§1§value" with value "json2"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§requestHeaderModifier§add§0§name" with value "Accept3"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§requestHeaderModifier§add§0§value" with value "json3"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§requestHeaderModifier§add§1§name" with value "Accept4"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§requestHeaderModifier§add§1§value" with value "json4"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§requestHeaderModifier§remove§0" with value "oldheader1"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§requestHeaderModifier§remove§1" with value "oldheader2"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§requestHeaderModifier§set§0§name" with value "Accept1"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§responseHeaderModifier§set§0§value" with value "json1"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§responseHeaderModifier§set§1§name" with value "Accept2"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§responseHeaderModifier§set§1§value" with value "json2"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§responseHeaderModifier§add§0§name" with value "Accept3"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§responseHeaderModifier§add§0§value" with value "json3"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§responseHeaderModifier§add§1§name" with value "Accept4"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§responseHeaderModifier§add§1§value" with value "json4"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§responseHeaderModifier§remove§0" with value "oldheader1"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§responseHeaderModifier§remove§1" with value "oldheader2"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§requestMirror§backendRef§group" with value "group1"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§requestMirror§backendRef§kind" with value "kind1"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§requestMirror§backendRef§namespace" with value "namespace1"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§requestMirror§backendRef§name" with value "name1"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§requestMirror§backendRef§port" with integer value "1"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§requestMirror§percent" with integer value "66"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§requestMirror§fraction§numerator" with integer value "11"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§requestMirror§fraction§denominator" with integer value "22"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§extensionRef§group" with value "group1"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§extensionRef§kind" with value "kind1"
* Test Object has key "spec§rules§0§backendRefs§0§filters§0§extensionRef§name" with value "name1"

___

* Clean the test execution folder